version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
  backend:
    build: ./backend
    restart: always,
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myappdb
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongodb_data: